routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [

	'uses' =>'FrontEndController@index',
	'as' =>'index'

]);

Route::get('/cart', [

	'uses' =>'CartController@index',
	'as' =>'cart'

]);


Route::post('/cart','CartController@store')->name('cart_add');

Route::delete('/cart/remove/{product}','CartController@destroy')->name('cart.destroy');

// Checkout
Route::get('/checkout','CheckoutController@index')->name('checkout');
Route::post('/checkout','CheckoutController@store')->name('checkout_pay');


Auth::routes();

Route::get('/Dashboard', 'HomeController@index')->name('Dashboard');

Route::resource('products', 'ProductsController');




Route::get('empty', function() {
    Cart::instance('default')->destroy();
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name','price','image','description'];



	public function getImageAttribute($image)
		{
			return asset($image);
		}
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use Session;
class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */ 
	public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        return view('products.index', ['products' => Product::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'price' => 'required',
            'image' => 'required|image'
        ]);

        $product = new Product;

        $product_image = $request->image;

        $product_image_new_name = time() . $product_image->getClientOriginalName();

        $product_image->move('uploads/products', $product_image_new_name);

        $product->name = $request->name;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->image = 'uploads/products/' . $product_image_new_name;

        $product->save();

        Session::flash('success', 'Product created.');

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
		
		return view('products.edit')->with('product', $product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'price' => 'required'
        ]);
        
        $product = Product::find($id);

        if($request->hasFile('image'))
        {
            $product_image = $request->image;

            $product_image_new_name = time() . $product_image->getClientOriginalName();

            $product_image->move('uploads/products', $product_image_new_name);

            $product->image = 'uploads/products/' . $product_image_new_name;

            $product->save();
        }

        $product->name = $request->name;
        $product->description = $request->description;
        $product->price = $request->price;
        

        $product->save();

        Session::flash('success', 'Product updated successfully.');

        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $product = Product::find($id);
        
        if(file_exists($product->image))
        {
            unlink($product->image);
        }

        $product->delete();

        Session::flash('success', 'Product deleted successfully.');

        return redirect()->back();
    }
}

resources/views/products/create.blade.php
@extends('layouts.master')

@section('page')
	Add New Product
@endsection

@section('content')
 
<!-- Basic Form-->
<div class="col-lg-10">
  <div class="card">
	<div class="card-header d-flex align-items-center">
	  <h3 class="h4">Add Product Form</h3>
	</div>
	<div class="card-body">
	 
	  <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
		<div class="form-group">
		  <label class="form-control-label">Product Name</label>
		  <input type="text" name="name" class="form-control" value="{{ old('name') }}">
		</div>
		<div class="form-group">       
		  <label class="form-control-label">Price</label>
		  <input type="number" name="price" class="form-control" value="{{ old('price') }}">
		</div>
		<div class="form-group">       
		  <label class="form-control-label">Product Image</label>
		  <input type="file" name="image" class="form-control">
		</div>
		<div class="form-group">
		  <label for="description">Description</label>
		  <textarea name="description" id="description" cols="10" rows="5" class="form-control">{{ old('description') }}</textarea>
		</div>
		<div class="form-group">       
		  <input type="submit" value="Add Product" class="btn btn-primary">
		</div>
	  </form>
	</div>
  </div>
</div>  
@endsection

resources/views/products/edit.blade.php
@extends('layouts.master')

@section('page')
	Edit Product
@endsection

@section('content')
 
<!-- Basic Form-->
<div class="col-lg-10">
  <div class="card">
	<div class="card-header d-flex align-items-center">
	  <h3 class="h4">Edit Product</h3>
	</div>
	<div class="card-body">
	 
	  <form action="{{ route('products.update', ['id' => $product->id ]) }}" method="post">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
		<div class="form-group">
			  <label for="name">Name</label>
			  <input type="text" name="name" value="{{ $product->name }}" class="form-control">
		</div>
		<div class="form-group">
			  <label for="image">Price</label>
			  <input type="number" name="price" value="{{ $product->price }}" class="form-control">
		</div>
		<div class="form-group">
			  <label for="image">Image</label>
			  <input type="file" name="image" class="form-control">
		</div>
		<div class="form-group">
			  <label for="description">Description</label>
			  <textarea name="description" id="description" cols="30" rows="10" class="form-control">{{ $product->description }}</textarea>
		</div>
		<div class="form-group">       
		  <input type="submit" value="Update Product" class="btn btn-primary">
		</div>
	  </form>
	</div>
  </div>
</div>  
@endsection

resources/views/products/index.blade.php
@extends('layouts.master')


@section('content')

<div class="card">
    <div class="card-header d-flex align-items-center">
	  <h3 class="h4">Product</h3>
	</div>

     <div class="card-body">
		<table class="table table-bordered">
		<thead>
			  <th>Name</th>
			  <th>Price</th>
			  <th>Image</th>
			  <th>Edit</th>
			  <th>Delete</th>
		</thead>
		<tbody>
			@foreach($products as $product)
			<tr>
			  <td>{{ $product->name }}</td>
			  <td>{{ $product->price }}</td>
			   <td><img src="{{$product->image}}" width="50px" height="50px"></td>
			  <td>
					<a href="{{ route('products.edit', ['id' => $product->id ]) }}" class="btn btn-default btn-xs">Edit</a>
			  </td>
			  <td>
					<form action="{{ route('products.destroy', ['id' => $product->id ]) }}" method="post">
						  
						  {{ method_field('DELETE')}}
						  {{ csrf_field() }}
						  <button class="btn btn-xs btn-danger">Delete</button>
					</form>
			  </td>
		</tr>
		@endforeach
		</tbody>
	</table>
    </div>
</div>

@endsection